### ISSUE TITLE
doesn't work!!!!1!1!1111!111!1!!!

### ISSUE THREAD

**Issue by piplup7575** [RuralAnemone/screenshot#1]
it doesn't work!11!1!1!!1!1!!

in all seriousness though, when testing, I get this error and nothing else happens
![image](https://user-images.githubusercontent.com/88395302/193127187-d0931bd3-8dd5-4849-ae04-7f80d6416d7c.png)

here is the console if that helps 
![image](https://user-images.githubusercontent.com/88395302/193127372-25c6fb04-0af7-4070-b6d4-c63b9798eea1.png)

let me know if this helps!

**Comment by RuralAnemone** [comment]
zamn

**Comment by RuralAnemone** [comment]
sounds like an issue with html2canvas

although it looks like you got the data url so it should be fine...?

**Comment by RuralAnemone** [comment]
oh wait no that's an issue with copying to the clipboard

**Comment by RuralAnemone** [comment]
right

**Comment by RuralAnemone** [comment]
but yeah I'm currently working on having a [jswindow](https://github.com/binbashbanana/jswindow) open up with the image in it and download/copy buttons and such idk

that'll be v1.0

**Comment by RuralAnemone** [comment]
*in order to fix that issue

**Comment by RuralAnemone** [comment]
should be in the projects tab now

**Comment by RuralAnemone** [comment]
yay now jswindows work :)

I'll close this when I've added the buttons and such to the window

**Comment by RuralAnemone** [comment]
wait no what am I thinking
the issue is resolved
aaaaaaaaaa
